[package]
  cjc-version = "1.1.0"
  name = "totp_cj"
  description = "Minimal TOTP library for Cangjie"
  version = "0.1.0"
  target-dir = ""
  src-dir = "src"
  output-type = "static"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]

[target]
  [target.x86_64-unknown-linux-gnu]
    [target.x86_64-unknown-linux-gnu.bin-dependencies]
      path-option = [ "${CANGJIE_STDX_PATH}" ]
