$:
  # Backend + frontend build, then (optionally) build & push Docker image.
  push:
    - &build_pipeline
      name: build
      # Import shared environment variables (e.g. CANGJIE_URL, STDX_URL).
      # CNB will fetch it with built-in credentials (CNB_TOKEN) during pipeline execution.
      imports:
        - https://cnb.cool/copurx/cangjie/-/blob/main/envs.yml
      runner:
        tags: cnb:arch:amd64
      docker:
        # Build a custom Ubuntu-based environment image first, then use it for all script jobs in this pipeline.
        build:
          dockerfile: .ide/Dockerfile
          by:
            - .ide/Dockerfile
          versionBy:
            - .ide/Dockerfile
        volumes:
          # pnpm store cache
          - main:/root/.local/share/pnpm:copy-on-write
          # cjpm / general caches
          - main:/root/.cache:copy-on-write
          - main:/root/.cjpm:copy-on-write
          # cache large downloaded SDK archives across builds
          - main:./build-script-cache:copy-on-write
      services:
        # Enable docker daemon (dind) + inject docker cli tools for docker build/push.
        - docker
      env:
        TZ: Asia/Shanghai
        # Avoid Next.js analytics/telemetry in CI.
        NEXT_TELEMETRY_DISABLED: "1"
      stages:
        - name: Show build environment versions
          script: |
            bash -lc '
              set -eux
              cat /etc/os-release || true
              bash --version | head -n 1
              node -v
              pnpm -v
              xmake --version
              clang --version | head -n 1
            '

        - name: Download Cangjie SDK + stdx
          script: |
            bash -lc '
              set -eux
              : "${CANGJIE_URL:?Missing env CANGJIE_URL (configure in CNB project variables)}"
              : "${STDX_URL:?Missing env STDX_URL (configure in CNB project variables)}"

              mkdir -p build-script-cache

              # Cangjie SDK
              if [ ! -d "./cangjie" ]; then
                wget -O build-script-cache/cangjie.tar.gz "$CANGJIE_URL"
                tar -xzf build-script-cache/cangjie.tar.gz
              fi

              # stdx
              if [ ! -d "./stdx" ]; then
                wget -O build-script-cache/stdx.zip "$STDX_URL"
                unzip -q build-script-cache/stdx.zip -d stdx
              fi
            '

        - name: Build backend (cjpm)
          script: |
            bash -lc '
              set -eux
              export XMAKE_ROOT=y
              export CANGJIE_STDX_PATH="$PWD/stdx"
              export CANGJIE_STDX="$PWD/stdx/linux_x86_64_llvm/dynamic/stdx"

              # envsetup.sh references LD_LIBRARY_PATH and may fail under `set -u` if it is unset.
              export LD_LIBRARY_PATH="${LD_LIBRARY_PATH:-}"
              set +u
              source ./cangjie/envsetup.sh
              set -u

              cjc -v
              cjpm build -V
            '

        - name: Build frontend (pnpm)
          script: |
            bash -lc '
              set -eux
              cd frontend
              pnpm install --frozen-lockfile
              pnpm run build
            '

        - name: Prepare runtime bundle (./app)
          script: |
            bash -lc '
              set -eux
              rm -rf app
              mkdir -p app/frontend app/plugins app/bin

              cp target/release/bin/main app/
              cp -r plugins app/plugins
              cp -r frontend/out app/frontend/out
            '

        - name: Package runtime bundle (zip)
          script: |
            bash -lc '
              set -eux
              mkdir -p dist
              rm -f "dist/app-${CNB_COMMIT_SHORT:-latest}.zip"
              (cd app && zip -qr "../dist/app-${CNB_COMMIT_SHORT:-latest}.zip" .)
              ls -lah dist
            '

        - name: Upload build artifacts (attachments)
          image: cnbcool/attachments:latest
          settings:
            attachments:
              - dist/app-*.zip

        - name: Bundle deno binary into ./app/bin
          script: |
            bash -lc '
              set -eux
              curl -fsSL https://deno.land/install.sh | sh
              cp ~/.deno/bin/deno ./app/bin/deno
              chmod +x ./app/main ./app/bin/deno
            '

        - name: Set CNB Docker image tag
          # Avoid pushing images from non-main branches / PR builds.
          if: test "$CNB_BRANCH" = "main"
          script: |
            bash -lc '
              set -eu
              # CNB provides built-in credentials; with `services: [docker]` we can push directly.
              printf "%s" "${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest"
            '
          exports:
            stdout: IMAGE_TAG

        - name: Docker build
          if: test "$CNB_BRANCH" = "main"
          script: |
            bash -lc '
              set -eux
              docker build -t "$IMAGE_TAG" .
            '

        - name: Docker push (CNB Docker registry)
          if: test "$CNB_BRANCH" = "main"
          script: |
            bash -lc '
              set -eux
              docker push "$IMAGE_TAG"
            '

    - &extension_pipeline
      name: extension
      ifModify:
        - extension/**
      docker:
        build:
          dockerfile: .ide/Dockerfile
          by:
            - .ide/Dockerfile
          versionBy:
            - .ide/Dockerfile
        volumes:
          - main:/root/.local/share/pnpm:copy-on-write
      env:
        NEXT_TELEMETRY_DISABLED: "1"
      stages:
        - name: Build & lint extension
          script: |
            bash -lc '
              set -eux
              cd extension
              pnpm install --frozen-lockfile
              pnpm run build
              pnpm run lint
            '

        - name: Package extension artifacts (zip)
          script: |
            bash -lc '
              set -eux
              command -v zip >/dev/null 2>&1 || (apt-get update && apt-get install -y --no-install-recommends zip && rm -rf /var/lib/apt/lists/*)
              mkdir -p dist
              rm -f "dist/extension-${CNB_COMMIT_SHORT:-latest}.zip"
              (cd extension/out && zip -qr "../../dist/extension-${CNB_COMMIT_SHORT:-latest}.zip" .)
              ls -lah dist
            '

        - name: Upload extension artifacts (attachments)
          image: cnbcool/attachments:latest
          settings:
            attachments:
              - dist/extension-*.zip

  pull_request:
    - *build_pipeline
    - *extension_pipeline
